### ISSUE TITLE
Can't record bag in ssd from python script

### ISSUE THREAD

**Issue by Kam0ss** [sonia-auv/proc_control#8]
The script made by @alexemdesgagne to send direct command to the motors is supposed to record bags automatically. 
But when launched, there is an error : 

Traceback (most recent call last):
  File "/home/babe/Workspaces/ros_sonia_ws/src/proc_control/script/ThrusterControlByValue.py", line 173, in <module>
    controller.start()
  File "/home/babe/Workspaces/ros_sonia_ws/src/proc_control/script/ThrusterControlByValue.py", line 88, in start
    self.launchBag()
  File "/home/babe/Workspaces/ros_sonia_ws/src/proc_control/script/ThrusterControlByValue.py", line 154, in launchBag
    **self.rosbag_proc = subprocess.Popen(command,cwd='/home/babe/data/control')**
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

I tried a lot of things, nothing works. Anyone has a clue of what is going on here ?

**Comment by 0x72D0** [comment]
I think Popen can't find a folder, did you have /home/babe/data/control on the computer you tested? Did you put a legit path into the bag name input?

**Comment by 0x72D0** [comment]
@alexemdesgagne maybe you should add exception handling on user input to avoid future problem with the script. Also create the correct folder if it dosen't exist.

**Comment by Kam0ss** [comment]
The folder exists on the Xavier, I tested the script there.
I also tested on my computer with another existing file, doesn't work. 

https://github.com/sonia-auv/proc_control/blob/722abe33c34f600fdd7cf13ca9579350d33f78c4/script/ThrusterControlByValue.py#L154

The cwd option is supposed to indicate where the command should be executed.

**Comment by coumarc9** [comment]
I think we should use the [rosbag api](http://wiki.ros.org/rosbag/Code%20API#Python_API) instead of subprocess
